// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jhnprdnztivhhcigocri.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpobnByZG56dGl2aGhjaWdvY3JpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMTMzNDksImV4cCI6MjA2NjY4OTM0OX0.nBdT-q7PpQ27ZrsEdjgOg0RwDJ4NmgOpQIhz03VYxdo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);